/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    players: Player;
    'player-mappings': PlayerMapping;
    campaigns: Campaign;
    worlds: World;
    rulesets: Ruleset;
    documents: Document;
    'game-sessions': GameSession;
    'provider-connections': ProviderConnection;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    players: PlayersSelect<false> | PlayersSelect<true>;
    'player-mappings': PlayerMappingsSelect<false> | PlayerMappingsSelect<true>;
    campaigns: CampaignsSelect<false> | CampaignsSelect<true>;
    worlds: WorldsSelect<false> | WorldsSelect<true>;
    rulesets: RulesetsSelect<false> | RulesetsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'game-sessions': GameSessionsSelect<false> | GameSessionsSelect<true>;
    'provider-connections': ProviderConnectionsSelect<false> | ProviderConnectionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'runtime-defaults': RuntimeDefault;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'runtime-defaults': RuntimeDefaultsSelect<false> | RuntimeDefaultsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  name: string;
  role: 'owner' | 'operator';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players".
 */
export interface Player {
  id: number;
  displayName: string;
  authProvider: 'guest' | 'google';
  email?: string | null;
  googleSub?: string | null;
  avatarUrl?: string | null;
  /**
   * Optional personal reference book that follows this player into the rooms they join.
   */
  personalRulebook?: (number | null) | Document;
  status: 'active' | 'suspended';
  quotaTier: 'standard' | 'priority' | 'internal';
  /**
   * Soft quota metadata for operator planning.
   */
  monthlySessionQuota?: number | null;
  /**
   * Soft quota metadata for voice usage planning.
   */
  monthlyVoiceMinutes?: number | null;
  canCreateRooms?: boolean | null;
  accessNotes?: string | null;
  preferredVoiceMode?: ('auto-vad' | 'push-to-talk' | 'text-only') | null;
  lastSeenAt?: string | null;
  lastRoomName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  slug: string;
  kind: 'primary-rulebook' | 'supporting-book' | 'lore-pack';
  status: 'uploaded' | 'indexing' | 'ready' | 'error';
  isActive?: boolean | null;
  isPrimary?: boolean | null;
  ruleset?: (number | null) | Ruleset;
  session?: (number | null) | GameSession;
  /**
   * When set, this document is owned by a player and can be managed from the player app.
   */
  ownerPlayer?: (number | null) | Player;
  /**
   * Check and save when you need a full re-index.
   */
  reindexRequested?: boolean | null;
  chunkCount?: number | null;
  lastIngestedAt?: string | null;
  ingestError?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rulesets".
 */
export interface Ruleset {
  id: number;
  title: string;
  slug: string;
  campaign?: (number | null) | Campaign;
  summary?: string | null;
  primaryRulebook?: (number | null) | Document;
  supportingBooks?: (number | Document)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns".
 */
export interface Campaign {
  id: number;
  title: string;
  slug: string;
  pitch?: string | null;
  tableExpectations?:
    | {
        expectation: string;
        id?: string | null;
      }[]
    | null;
  primaryRuleset?: (number | null) | Ruleset;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-sessions".
 */
export interface GameSession {
  id: number;
  title: string;
  slug: string;
  status: 'scheduled' | 'live' | 'ended';
  roomName: string;
  /**
   * When enabled, the room can appear in the player app and accept sign-ins.
   */
  allowGuests?: boolean | null;
  /**
   * When disabled, the room is hidden from the player app and public join flow.
   */
  publicJoinEnabled?: boolean | null;
  scheduledFor?: string | null;
  campaign?: (number | null) | Campaign;
  world?: (number | null) | World;
  ruleset?: (number | null) | Ruleset;
  /**
   * Only these signed-in players can see and enter the room when the room is not open to all players.
   */
  allowedPlayers?: (number | Player)[] | null;
  activeDocuments?: (number | Document)[] | null;
  publicSummary?: string | null;
  welcomeText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "worlds".
 */
export interface World {
  id: number;
  title: string;
  slug: string;
  campaign?: (number | null) | Campaign;
  tone?: string | null;
  playerPromise?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-mappings".
 */
export interface PlayerMapping {
  id: number;
  mappingKey: string;
  session: number | GameSession;
  livekitIdentity: string;
  participantLabel: string;
  mappedName: string;
  isConfirmed?: boolean | null;
  confirmedBy?: (number | null) | Player;
  speakingNotes?: string | null;
  lastConfirmedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provider-connections".
 */
export interface ProviderConnection {
  id: number;
  label: string;
  slug: string;
  provider: 'gemini' | 'openai' | 'deepgram' | 'livekit';
  enabled?: boolean | null;
  llmModel?: string | null;
  sttModel?: string | null;
  ttsModel?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'players';
        value: number | Player;
      } | null)
    | ({
        relationTo: 'player-mappings';
        value: number | PlayerMapping;
      } | null)
    | ({
        relationTo: 'campaigns';
        value: number | Campaign;
      } | null)
    | ({
        relationTo: 'worlds';
        value: number | World;
      } | null)
    | ({
        relationTo: 'rulesets';
        value: number | Ruleset;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'game-sessions';
        value: number | GameSession;
      } | null)
    | ({
        relationTo: 'provider-connections';
        value: number | ProviderConnection;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "players_select".
 */
export interface PlayersSelect<T extends boolean = true> {
  displayName?: T;
  authProvider?: T;
  email?: T;
  googleSub?: T;
  avatarUrl?: T;
  personalRulebook?: T;
  status?: T;
  quotaTier?: T;
  monthlySessionQuota?: T;
  monthlyVoiceMinutes?: T;
  canCreateRooms?: T;
  accessNotes?: T;
  preferredVoiceMode?: T;
  lastSeenAt?: T;
  lastRoomName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "player-mappings_select".
 */
export interface PlayerMappingsSelect<T extends boolean = true> {
  mappingKey?: T;
  session?: T;
  livekitIdentity?: T;
  participantLabel?: T;
  mappedName?: T;
  isConfirmed?: T;
  confirmedBy?: T;
  speakingNotes?: T;
  lastConfirmedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns_select".
 */
export interface CampaignsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pitch?: T;
  tableExpectations?:
    | T
    | {
        expectation?: T;
        id?: T;
      };
  primaryRuleset?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "worlds_select".
 */
export interface WorldsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  campaign?: T;
  tone?: T;
  playerPromise?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rulesets_select".
 */
export interface RulesetsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  campaign?: T;
  summary?: T;
  primaryRulebook?: T;
  supportingBooks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kind?: T;
  status?: T;
  isActive?: T;
  isPrimary?: T;
  ruleset?: T;
  session?: T;
  ownerPlayer?: T;
  reindexRequested?: T;
  chunkCount?: T;
  lastIngestedAt?: T;
  ingestError?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-sessions_select".
 */
export interface GameSessionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  roomName?: T;
  allowGuests?: T;
  publicJoinEnabled?: T;
  scheduledFor?: T;
  campaign?: T;
  world?: T;
  ruleset?: T;
  allowedPlayers?: T;
  activeDocuments?: T;
  publicSummary?: T;
  welcomeText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provider-connections_select".
 */
export interface ProviderConnectionsSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  provider?: T;
  enabled?: T;
  llmModel?: T;
  sttModel?: T;
  ttsModel?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runtime-defaults".
 */
export interface RuntimeDefault {
  id: number;
  systemPrompt: string;
  llmProvider?: ('gemini' | 'openai') | null;
  llmModel?: string | null;
  sttProvider?: ('deepgram' | 'openai') | null;
  sttModel?: string | null;
  ttsProvider?: ('deepgram' | 'openai') | null;
  ttsModel?: string | null;
  ttsVoice?: string | null;
  voiceMode?: ('auto-vad' | 'push-to-talk') | null;
  retrievalTopK?: number | null;
  maxParticipants?: number | null;
  allowTextFallback?: boolean | null;
  joinGreeting?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteTitle: string;
  tagline?: string | null;
  publicDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "runtime-defaults_select".
 */
export interface RuntimeDefaultsSelect<T extends boolean = true> {
  systemPrompt?: T;
  llmProvider?: T;
  llmModel?: T;
  sttProvider?: T;
  sttModel?: T;
  ttsProvider?: T;
  ttsModel?: T;
  ttsVoice?: T;
  voiceMode?: T;
  retrievalTopK?: T;
  maxParticipants?: T;
  allowTextFallback?: T;
  joinGreeting?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  tagline?: T;
  publicDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}